name: hvstat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - numpy=1.23.5
  - pandas=1.4.4
  - scipy
  - matplotlib
  - seaborn
  - statsmodels
  - netcdf4
  - openpyxl
  - xlrd
  - pytables
  - rtree
  - shapely
  - pyshp
  - rasterio
  - conda-forge::geopandas
  - conda-forge::fiona
  - conda-forge::gdal
  - ipykernel
  - ipywidgets
  - python-kaleido
  - papermill
  - conda-forge::python-docx